/* device:       /project/Tera_7 */
/* device model: TERA7 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__SCREENFRAME_C
#define INCLUDE__VT3_EVENT__SCREENFRAME_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__ScreenFrame.h"
#include "vt3_Event__ScreenFrame.h"
#include "vt3_extra.h"
#include "version_vt3_runtime.h"
#include "version_pdfrender.h"

/* timer event handler for screen frame: /project/Tera_7/screen_frame */
void vt3_event_ind_screen_frame(BYTE event)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/screen_frame
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: screen_frame */


/* timer event handler for physical indicator: /project/Tera_7/screen_frame/screen_backlight */
void vt3_event_ind_screen_frame_screen_backlight(
	BYTE event, 
	vt3_indicator_PhysicalIndicator FARPTR ind)
{
	ind->currentValue = ((BacklightTera));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/screen_frame/screen_backlight
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: screen_backlight */


/* timer event handler for physical indicator: /project/Tera_7/screen_frame/buzzer */
void vt3_event_ind_screen_frame_buzzer(
	BYTE event, 
	vt3_indicator_PhysicalIndicator FARPTR ind)
{
	ind->currentValue = ((BuzzerTera));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/screen_frame/buzzer
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: buzzer */


/* timer event handler for physical indicator: /project/Tera_7/screen_frame/keys_backlight */
void vt3_event_ind_screen_frame_keys_backlight(
	BYTE event, 
	vt3_indicator_PhysicalIndicator FARPTR ind)
{
	ind->currentValue = ((BacklightTera));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/screen_frame/keys_backlight
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: keys_backlight */


#endif /* INCLUDE__VT3_EVENT__SCREENFRAME_C */

/* end of file */
