/* device:       /project/Tera_7 */
/* device model: TERA7 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__CAMERA2_C
#define INCLUDE__VT3_EVENT__CAMERA2_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__Camera2.h"
#include "vt3_Event__Camera2.h"
#include "vt3_extra.h"
#include "version_vt3_runtime.h"
#include "version_pdfrender.h"

/* timer event handler for screen: /project/Tera_7/Screens/camera_2 */
void vt3_event_ind_camera_2(BYTE event)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/camera_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
		
	    /*Exit Camera_2 to Home Screen */
	    if ((ind_screen_frame_key_F10).eventDown)
	        {
	          reqScreen = SCREEN_HOME;           
	        }
	        
	    if (vt3_screen != reqScreen)
	    {
	        vt3_screen = reqScreen;
	    }
	    
	
	}

} /* end of event code for indicator: camera_2 */


/* timer event handler for indicator: /project/Tera_7/Screens/camera_2/F10/Button 
 * runs every 100ms
 */
void vt3_event_ind_camera_2_F10_Button(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/camera_2/F10/Button
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: Button */


/* timer event handler for indicator: /project/Tera_7/Screens/camera_2/F10/Text_1 
 * runs every 100ms
 */
void vt3_event_ind_camera_2_F10_Text_1(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(4) FAR _str = { 4, 4, "EXIT" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/camera_2/F10/Text_1
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: Text_1 */


#endif /* INCLUDE__VT3_EVENT__CAMERA2_C */

/* end of file */
