/* device:       /project/Tera_7 */
/* device model: TERA7 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__SPLASH_C
#define INCLUDE__VT3_EVENT__SPLASH_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__Splash.h"
#include "vt3_Event__Splash.h"
#include "vt3_extra.h"
#include "version_vt3_runtime.h"
#include "version_pdfrender.h"

/* timer event handler for screen: /project/Tera_7/Screens/splash */
void vt3_event_ind_splash(BYTE event)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/splash
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	    splashCounter ++;
	    
		if (splashCounter == 30)
	    {
	        updateEnable = (TRUE);
	        if (rebootThenUpdate == 0)
	        {
	            reqScreen = SCREEN_HOME;
	        }
	    }
	    
	    if (vt3_screen != reqScreen)
	    {
	        vt3_screen = reqScreen;
	    }
	
	}

} /* end of event code for indicator: splash */


/* timer event handler for indicator: /project/Tera_7/Screens/splash/multibitmap 
 * runs every 100ms
 */
void vt3_event_ind_splash_multibitmap(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/splash/multibitmap
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multibitmap */


#endif /* INCLUDE__VT3_EVENT__SPLASH_C */

/* end of file */
