/* device:       /project/Tera_7 */
/* device model: TERA7 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__SETUP_C
#define INCLUDE__VT3_EVENT__SETUP_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__Setup.h"
#include "vt3_Event__Setup.h"
#include "vt3_extra.h"
#include "version_vt3_runtime.h"
#include "version_pdfrender.h"

/* timer event handler for screen: /project/Tera_7/Screens/setup */
void vt3_event_ind_setup(BYTE event)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	    /* Move Paramter Cursor Index Up/Down */
	    if ((Parameter_Index == 0) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	        Parameter_Index = 7; 
	        }
	    else if ((Parameter_Index == 0) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	        Parameter_Index = 1; 
	        }
	    else if ((Parameter_Index == 1) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	        Parameter_Index = 7; 
	        }
	    else if ((Parameter_Index == 1) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	        Parameter_Index = 2; 
	        }
	    else if ((Parameter_Index == 2) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	        Parameter_Index = 1; 
	        }
	    else if ((Parameter_Index == 2) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	        Parameter_Index = 3; 
	        }
	    else if ((Parameter_Index == 3) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	        Parameter_Index = 2; 
	        }
	    else if ((Parameter_Index == 3) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	        Parameter_Index = 4; 
	        }
	    else if ((Parameter_Index == 4) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	        Parameter_Index = 3; 
	        }
	    else if ((Parameter_Index == 4) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	        Parameter_Index = 5; 
	        }
	    else if ((Parameter_Index == 5) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	        Parameter_Index = 4; 
	        }
	    else if ((Parameter_Index == 5) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	        Parameter_Index = 6; 
	        }
	    else if ((Parameter_Index == 6) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	        Parameter_Index = 5; 
	        }
	    else if ((Parameter_Index == 6) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	        Parameter_Index = 7; 
	        }
	    else if ((Parameter_Index == 7) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	        Parameter_Index = 6; 
	        }
	    else if ((Parameter_Index == 7) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	        Parameter_Index = 1; 
	        }
	     else if ((Parameter_Index == 8) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	        Parameter_Index = 7; 
	        }
	    else if ((Parameter_Index == 8) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	        Parameter_Index = 1; 
	        }
	        
	    /*Select and Exit Parameter Selection*/
	    if ((Parameter_Index > 0) &&
	        (Parameter_Index < 10) &&
	        ((ind_screen_frame_key_F15).eventDown))
	        {
	        Parameter_Index = (Parameter_Index + 10); 
	        }
	    else if ((Parameter_Index >10) &&
	        (Parameter_Index <20) &&
	        ((ind_screen_frame_key_F15).eventDown))
	        {
	        Parameter_Index = (Parameter_Index - 10); 
	        }
	    
	    /*Highlight Paramter Field */
	    if (Parameter_Index == 1)
	    {
	    BG_Color_1 = 1;    
	    }
	    else
	    {
	    BG_Color_1 = 0;    
	    }
	    
	    if (Parameter_Index == 11)
	    {
	    BG_Color_1_1 = 1;    
	    }
	    else
	    {
	    BG_Color_1_1 = 0;    
	    }
	    
	    if (Parameter_Index == 2)
	    {
	    BG_Color_2 = 1;    
	    }
	    else
	    {
	    BG_Color_2 = 0;    
	    }
	    if (Parameter_Index == 12)
	    {
	    BG_Color_2_1 = 1;    
	    }
	    else
	    {
	    BG_Color_2_1 = 0;   
	    }
	    if (Parameter_Index == 3)
	    {
	    BG_Color_3 = 1;    
	    }
	    else
	    {
	    BG_Color_3 = 0;  
	    }
	    if (Parameter_Index == 13)
	    {
	    BG_Color_3_1 = 1;    
	    }
	    else
	    {
	    BG_Color_3_1 = 0;  
	    }
	    if (Parameter_Index == 4)
	    {
	    BG_Color_4 = 1;    
	    }
	    else
	    {
	    BG_Color_4 = 0;  
	    }
	    
	    if (Parameter_Index == 14)
	    {
	    BG_Color_4_1 = 1;    
	    }
	    else
	    {
	    BG_Color_4_1 = 0;  
	    }
	      
	    if (Parameter_Index == 5)
	    {
	    BG_Color_5 = 1;    
	    }
	    else
	    {
	    BG_Color_5 = 0;
	    }
	    if (Parameter_Index == 15)
	    {
	    BG_Color_5_1 = 1;    
	    }
	    else
	    {
	    BG_Color_5_1 = 0;
	    }
	    if (Parameter_Index == 6)
	    {
	    BG_Color_6 = 1;    
	    }
	    else
	    {
	    BG_Color_6 = 0; 
	    }
	    if (Parameter_Index == 16)
	    {
	    BG_Color_6_1 = 1;    
	    }
	    else
	    {
	    BG_Color_6_1 = 0; 
	    }
	    if (Parameter_Index == 7)
	    {
	    BG_Color_7 = 1;    
	    }
	    else
	    {
	    BG_Color_7 = 0;  
	    }
	    if (Parameter_Index == 17)
	    {
	    BG_Color_7_1 = 1;    
	    }
	    else
	    {
	    BG_Color_7_1 = 0; 
	    }
	    if (Parameter_Index == 8)
	    {
	    BG_Color_8 = 1;    
	    }
	    else
	    {
	    BG_Color_8 = 0;  
	    }
	    if (Parameter_Index == 18)
	    {
	    BG_Color_8_1 = 1;    
	    }
	    else
	    {
	    BG_Color_8_1 = 0;  
	    }
	    /*Set AC Setpoint Parameter */
	    ACMinSetting = (p_HeatSetPoint + p_HeatDeadband + 10);
	    
	    if (((Parameter_Index == 11) && 
	        (p_ACSetPoint < 99)) &&
	        (((ind_screen_frame_key_F11).eventDown) ||
	            ((ind_screen_frame_key_F11).pressedTime > 3000)))
	        {
	         p_ACSetPoint ++;   
	        }
	    else if ((Parameter_Index == 11) && 
	        (p_ACSetPoint == 99) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	         p_ACSetPoint = ACMinSetting; //40  
	        }
	    else if (((Parameter_Index == 11) && 
	        (p_ACSetPoint > ACMinSetting)) && //41
	        (((ind_screen_frame_key_F12).eventDown) ||
	            ((ind_screen_frame_key_F12).pressedTime > 3000)))
	        {
	         p_ACSetPoint --;   
	        }
	    else if ((Parameter_Index == 11) && 
	        (p_ACSetPoint == ACMinSetting) && //
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	         p_ACSetPoint = 99;   
	        }
	    if (p_ACSetPoint < ACMinSetting)
	        {
	        p_ACSetPoint = ACMinSetting;
	        }
	     /*Set AC Deadband Parameter */
	    if (((Parameter_Index == 12) && 
	        (p_ACDeadband < 20)) &&
	        (((ind_screen_frame_key_F11).eventDown) ||
	        ((ind_screen_frame_key_F11).pressedTime > 3000)))
	        {
	         p_ACDeadband ++;   
	        }
	    else if ((Parameter_Index == 12) && 
	        (p_ACDeadband == 20) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	         p_ACDeadband = 1;   
	        }
	    else if (((Parameter_Index == 12) && 
	        (p_ACDeadband > 1)) &&
	        (((ind_screen_frame_key_F12).eventDown) ||
	        ((ind_screen_frame_key_F12).pressedTime > 3000)))        
	        {
	         p_ACDeadband --;   
	        }
	    else if ((Parameter_Index == 12) && 
	        (p_ACDeadband == 1) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	         p_ACDeadband = 20;   
	        }
	    
	     /*Set Heat Setpoint Parameter */
	     HeatMaxSetting = (p_ACSetPoint - (p_ACDeadband + 10)); 
	     
	    if (((Parameter_Index == 13) && 
	        (p_HeatSetPoint < HeatMaxSetting)) && //99
	        (((ind_screen_frame_key_F11).eventDown) ||
	        ((ind_screen_frame_key_F11).pressedTime > 3000)))
	        {
	         p_HeatSetPoint ++;   
	        }
	    else if ((Parameter_Index == 13) && 
	        (p_HeatSetPoint == HeatMaxSetting) && //99
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	         p_HeatSetPoint = 0;   
	        }
	    else if (((Parameter_Index == 13) && 
	        (p_HeatSetPoint > 0)) &&
	        (((ind_screen_frame_key_F12).eventDown) ||
	        ((ind_screen_frame_key_F12).pressedTime > 3000)))
	        {
	         p_HeatSetPoint --;   
	        }
	    else if ((Parameter_Index == 13) && 
	        (p_HeatSetPoint == 0) && //40
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	         p_HeatSetPoint = HeatMaxSetting;   
	        }
	    if (p_HeatSetPoint > HeatMaxSetting)
	        {
	        p_HeatSetPoint = HeatMaxSetting;
	        }
	        
	     /*Set Heat Deadband Parameter */
	    if (((Parameter_Index == 14) && 
	        (p_HeatDeadband < 20)) &&
	        (((ind_screen_frame_key_F11).eventDown) ||
	        ((ind_screen_frame_key_F11).pressedTime > 3000)))
	        {
	         p_HeatDeadband ++;   
	        }
	    else if ((Parameter_Index == 14) && 
	        (p_HeatDeadband == 20) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	         p_HeatDeadband = 1;   
	        }
	    else if (((Parameter_Index == 14) && 
	        (p_HeatDeadband > 1)) &&
	        (((ind_screen_frame_key_F12).eventDown) ||
	        ((ind_screen_frame_key_F12).pressedTime > 3000)))
	        {
	         p_HeatDeadband --;   
	        }
	    else if ((Parameter_Index == 14) && 
	        (p_HeatDeadband == 1) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	         p_HeatDeadband = 20;   
	        }
	        
	    /*Set Lower Alarm Parameter */
	    if (((Parameter_Index == 15) && 
	        (p_LowerAlarmSetPoint < 150)) &&
	        (((ind_screen_frame_key_F11).eventDown) ||
	        ((ind_screen_frame_key_F11).pressedTime > 3000)))
	        {
	         p_LowerAlarmSetPoint ++;   
	        }
	    else if ((Parameter_Index == 15) && 
	        (p_LowerAlarmSetPoint == 150) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	         p_LowerAlarmSetPoint = 0;   
	        }
	    else if (((Parameter_Index == 15) && 
	        (p_LowerAlarmSetPoint > 0)) &&
	        (((ind_screen_frame_key_F12).eventDown) ||
	        ((ind_screen_frame_key_F12).pressedTime > 3000)))
	        {
	         p_LowerAlarmSetPoint --;   
	        }
	    else if ((Parameter_Index == 15) && 
	        (p_LowerAlarmSetPoint == 0) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	         p_LowerAlarmSetPoint = 150;   
	        }
	        
	    /*Set Upper Alarm Parameter */
	    if (((Parameter_Index == 16) && 
	        (p_UpperAlarmSetPoint < 150)) &&
	        (((ind_screen_frame_key_F11).eventDown) ||
	        ((ind_screen_frame_key_F11).pressedTime > 3000)))
	        {
	         p_UpperAlarmSetPoint ++;   
	        }
	    else if ((Parameter_Index == 16) && 
	        (p_UpperAlarmSetPoint == 150) &&
	        ((ind_screen_frame_key_F11).eventDown))
	        {
	         p_UpperAlarmSetPoint = 0;   
	        }
	    else if (((Parameter_Index == 16) && 
	        (p_UpperAlarmSetPoint > 0)) &&
	        (((ind_screen_frame_key_F12).eventDown) ||
	        ((ind_screen_frame_key_F12).pressedTime > 3000)))
	        {
	         p_UpperAlarmSetPoint --;   
	        }
	    else if ((Parameter_Index == 16) && 
	        (p_UpperAlarmSetPoint == 0) &&
	        ((ind_screen_frame_key_F12).eventDown))
	        {
	         p_UpperAlarmSetPoint = 150;   
	        }
	    
	
	     
	     /* Set Set-Up Screen Save Flag*/
	     SetupSaveFlag = 1;
	     
	     
		/*Exit Setup to Home Screen */
	    if ((ind_screen_frame_key_F10).eventDown)
	        {
	          reqScreen = SCREEN_HOME;           
	        }
	        
	    if (vt3_screen != reqScreen)
	    {
	        vt3_screen = reqScreen;
	    }
	
	}

} /* end of event code for indicator: setup */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Logo/multibitmap 
 * runs every 100ms
 */
void vt3_event_ind_setup_Logo_multibitmap(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Logo/multibitmap
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multibitmap */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/BG_1 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_BG_1(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_1));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/BG_1
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_1 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/BG_1_1 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_BG_1_1(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_1_1));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/BG_1_1
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_1_1 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/BG_2 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_BG_2(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_2));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/BG_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_2 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/BG_2_2 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_BG_2_2(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_2_1));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/BG_2_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_2_2 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/ac_setpoint_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_ac_setpoint_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(12) FAR _str = { 12, 12, "AC SETPOINT:" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/ac_setpoint_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: ac_setpoint_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/ac_setpoint_number 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_ac_setpoint_number(
	BYTE event, 
	vt3_indicator_NumberEditable FARPTR ind)
{
	if ( event == VT3_DISP_EVENT_OPEN )
	{
		ind->currentValue = (p_ACSetPoint);
	}
	else if( !vt3_has_focus((const vt3_indicator_abstract FARPTR) ind) )
	{
		ind->currentValue = (p_ACSetPoint);
	}
	else
	{
		(p_ACSetPoint) = (UINT)ind->currentValue;
	}

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/ac_setpoint_number
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: ac_setpoint_number */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/ac_sp_unit_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_ac_sp_unit_text(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((p_Units));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/ac_sp_unit_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: ac_sp_unit_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/ac_sp_degree_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_ac_sp_degree_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(1) FAR _str = { 1, 1, "o" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/ac_sp_degree_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: ac_sp_degree_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/ac_deadband_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_ac_deadband_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(12) FAR _str = { 12, 12, "AC DEADBAND:" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/ac_deadband_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: ac_deadband_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/ac_deadband_number 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_ac_deadband_number(
	BYTE event, 
	vt3_indicator_NumberEditable FARPTR ind)
{
	if ( event == VT3_DISP_EVENT_OPEN )
	{
		ind->currentValue = (p_ACDeadband);
	}
	else if( !vt3_has_focus((const vt3_indicator_abstract FARPTR) ind) )
	{
		ind->currentValue = (p_ACDeadband);
	}
	else
	{
		(p_ACDeadband) = (UINT)ind->currentValue;
	}

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/ac_deadband_number
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: ac_deadband_number */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/ac_db_unit_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_ac_db_unit_text(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((p_Units));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/ac_db_unit_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: ac_db_unit_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/AC/ac_db_degree_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_AC_ac_db_degree_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(1) FAR _str = { 1, 1, "o" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/AC/ac_db_degree_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: ac_db_degree_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/BG_3 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_BG_3(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_3));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/BG_3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_3 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/BG_3_1 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_BG_3_1(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_3_1));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/BG_3_1
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_3_1 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/BG_4 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_BG_4(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_4));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/BG_4
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_4 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/BG_4_1 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_BG_4_1(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_4_1));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/BG_4_1
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_4_1 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/heat_setpoint_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_heat_setpoint_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(14) FAR _str = { 14, 14, "HEAT SETPOINT:" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/heat_setpoint_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: heat_setpoint_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/heat_setpoint_number 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_heat_setpoint_number(
	BYTE event, 
	vt3_indicator_NumberEditable FARPTR ind)
{
	if ( event == VT3_DISP_EVENT_OPEN )
	{
		ind->currentValue = (p_HeatSetPoint);
	}
	else if( !vt3_has_focus((const vt3_indicator_abstract FARPTR) ind) )
	{
		ind->currentValue = (p_HeatSetPoint);
	}
	else
	{
		(p_HeatSetPoint) = (UINT)ind->currentValue;
	}

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/heat_setpoint_number
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: heat_setpoint_number */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/heat_sp_unit_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_heat_sp_unit_text(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((p_Units));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/heat_sp_unit_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: heat_sp_unit_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/heat_sp_degree_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_heat_sp_degree_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(1) FAR _str = { 1, 1, "o" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/heat_sp_degree_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: heat_sp_degree_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/heat_deadband_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_heat_deadband_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(14) FAR _str = { 14, 14, "HEAT DEADBAND:" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/heat_deadband_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: heat_deadband_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/heat_deadband_number 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_heat_deadband_number(
	BYTE event, 
	vt3_indicator_NumberEditable FARPTR ind)
{
	if ( event == VT3_DISP_EVENT_OPEN )
	{
		ind->currentValue = (p_HeatDeadband);
	}
	else if( !vt3_has_focus((const vt3_indicator_abstract FARPTR) ind) )
	{
		ind->currentValue = (p_HeatDeadband);
	}
	else
	{
		(p_HeatDeadband) = (UINT)ind->currentValue;
	}

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/heat_deadband_number
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: heat_deadband_number */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/heat_db_unit_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_heat_db_unit_text(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((p_Units));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/heat_db_unit_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: heat_db_unit_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/Heat/heat_db_degree_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_Heat_heat_db_degree_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(1) FAR _str = { 1, 1, "o" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/Heat/heat_db_degree_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: heat_db_degree_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/BG_5 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_BG_5(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_5));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/BG_5
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_5 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/BG_5_1 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_BG_5_1(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_5_1));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/BG_5_1
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_5_1 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/BG_6 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_BG_6(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_6));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/BG_6
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_6 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/BG_6_1 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_BG_6_1(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = ((BG_Color_6_1));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/BG_6_1
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: BG_6_1 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/lower_alarm_setpoint_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_lower_alarm_setpoint_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(21) FAR _str = { 21, 21, "LOWER ALARM SETPOINT:" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/lower_alarm_setpoint_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: lower_alarm_setpoint_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/lower_alarm_setpoint_number 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_lower_alarm_setpoint_number(
	BYTE event, 
	vt3_indicator_NumberEditable FARPTR ind)
{
	if ( event == VT3_DISP_EVENT_OPEN )
	{
		ind->currentValue = (p_LowerAlarmSetPoint);
	}
	else if( !vt3_has_focus((const vt3_indicator_abstract FARPTR) ind) )
	{
		ind->currentValue = (p_LowerAlarmSetPoint);
	}
	else
	{
		(p_LowerAlarmSetPoint) = (UINT)ind->currentValue;
	}

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/lower_alarm_setpoint_number
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: lower_alarm_setpoint_number */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/lower_alarm_sp_unit_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_lower_alarm_sp_unit_text(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((p_Units));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/lower_alarm_sp_unit_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: lower_alarm_sp_unit_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/lower_alarm_sp_degree_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_lower_alarm_sp_degree_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(1) FAR _str = { 1, 1, "o" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/lower_alarm_sp_degree_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: lower_alarm_sp_degree_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/upper_alarm_setpoint_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_upper_alarm_setpoint_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(21) FAR _str = { 21, 21, "UPPER ALARM SETPOINT:" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/upper_alarm_setpoint_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: upper_alarm_setpoint_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/upper_alarm_setpoint_number 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_upper_alarm_setpoint_number(
	BYTE event, 
	vt3_indicator_NumberEditable FARPTR ind)
{
	if ( event == VT3_DISP_EVENT_OPEN )
	{
		ind->currentValue = (p_UpperAlarmSetPoint);
	}
	else if( !vt3_has_focus((const vt3_indicator_abstract FARPTR) ind) )
	{
		ind->currentValue = (p_UpperAlarmSetPoint);
	}
	else
	{
		(p_UpperAlarmSetPoint) = (UINT)ind->currentValue;
	}

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/upper_alarm_setpoint_number
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: upper_alarm_setpoint_number */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/upper_alarm_setpoint_unit_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_upper_alarm_setpoint_unit_text(
	BYTE event, 
	vt3_indicator_MultiText FARPTR ind)
{
	ind->currentValue = ((p_Units));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/upper_alarm_setpoint_unit_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: upper_alarm_setpoint_unit_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/HVAC_Alarms/upper_alarm_setpoint_degree_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_HVAC_Alarms_upper_alarm_setpoint_degree_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(1) FAR _str = { 1, 1, "o" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/HVAC_Alarms/upper_alarm_setpoint_degree_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: upper_alarm_setpoint_degree_text */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/F10/Button 
 * runs every 100ms
 */
void vt3_event_ind_setup_F10_Button(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/F10/Button
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: Button */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/F10/Text_1 
 * runs every 100ms
 */
void vt3_event_ind_setup_F10_Text_1(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(4) FAR _str = { 4, 4, "EXIT" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/F10/Text_1
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: Text_1 */


/* timer event handler for indicator: /project/Tera_7/Screens/setup/simple_text 
 * runs every 100ms
 */
void vt3_event_ind_setup_simple_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(148) FAR _str = { 148, 148, "Use the Up/Down Arrow Keys to make parmeter selection \n and then press Enter. Use the Up/Down Arrow Keys to \n change the value and then press Enter." };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/setup/simple_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text */


#endif /* INCLUDE__VT3_EVENT__SETUP_C */

/* end of file */
