/* device:       /project/Tera_7 */
/* device model: TERA7 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__CAMERA_C
#define INCLUDE__VT3_EVENT__CAMERA_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__Camera.h"
#include "vt3_Event__Camera.h"
#include "vt3_extra.h"
#include "version_vt3_runtime.h"
#include "version_pdfrender.h"

/* timer event handler for screen: /project/Tera_7/Screens/camera */
void vt3_event_ind_camera(BYTE event)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Screens/camera
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
		
	    if (IO_ReverseGear == 0)
	    {
	        reqScreen = SCREEN_HOME;
	        
	        if (vt3_screen != reqScreen)
	        {
	            vt3_screen = reqScreen;
	        }
	    }
	    
	
	}

} /* end of event code for indicator: camera */


#endif /* INCLUDE__VT3_EVENT__CAMERA_C */

/* end of file */
