/* device:       /project/Tera_7 */
/* device model: TERA7 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_POU__OUTPUTS_C
#define INCLUDE__VT3_POU__OUTPUTS_C

#include "vt3_base.h"
#include "vt3_POU_common.h"
#include "vt3_extra.h"
#include "version_vt3_runtime.h"
#include "version_pdfrender.h"
#include "vt3_POU__GET_POWER_FAIL.h"
#include "vt3_POU__SET_POWER_FAIL_SHUTDOWN.h"
#include "vt3_POU__SHUTDOWN.h"
#include "vt3_POU__REBOOT.h"
#include "vt3_POU__INIT_SD_USB.h"
#include "vt3_POU__WRITE_EL_TO_SD.h"
#include "vt3_POU__WRITE_EL_TO_USB.h"
#include "vt3_POU__WRITE_EL_ENUM.h"
#include "vt3_POU__WRITE_EL.h"
#include "vt3_POU__WRITE_EL_PRIVATE.h"
#include "vt3_POU__INIT_BYTEARRAY_P.h"
#include "vt3_POU__INIT_BYTEARRAY_R.h"
#include "vt3_POU__check_touchcalibration.h"
#include "vt3_POU__req_touchcalibration.h"
#include "vt3_POU__mountUSB.h"
#include "vt3_POU__mountSD.h"
#include "vt3_POU__umountUSB.h"
#include "vt3_POU__umountSD.h"
#include "vt3_POU__lcdSetBlank.h"
#include "vt3_POU__get_prj_version.h"
#include "vt3_POU__get_prj_version_byte.h"
#include "vt3_POU__ARR_BYTE_version.h"
#include "vt3_POU__BYTE_TO_ASCII.h"
#include "vt3_POU__ST_TRANSLATE.h"



/* initializers of addressed variables */

/* table of initializators of addressed variables */
static const vt3_screen_initializer FAR __init_table__outputs[] = {
	{ NULL, NULL, 0 } /* sentinel */
}; /* __init_table__outputs[] */

/* initializers of in_out parameters */

/* POU constants */
/* end of POU constants */

/* initialize values for POU status */
static const outputs_t FAR __const__outputs__param_init = 
{
	/* EN                   */ TRUE,
	/* ENO                  */ TRUE,
}; /* end of __const__outputs__param_init */

/* initialization of PROGRAM status */
void outputs__init(void)
{
	const vt3_screen_initializer FARPTR p;

	/* initialize addressed variables */
	for ( p = __init_table__outputs; p->len; p ++ )
	{
		FarMemCopy(p->dst, p->src, p->len);
	}

	/* initialize local data */
	FarMemCopy(&outputs, &__const__outputs__param_init, sizeof __const__outputs__param_init);

	/* initialize function block instances */
}

/* PROGRAM execution */
void outputs__call(void)
{
	/* local variables */
	/* end of local variables */

	/* preamble: conditional execution */
	outputs.ENO = outputs.EN;
	if ( ! outputs.EN )
	{
		return;
	}


	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/Tera_7/Programs/PLC_PRG_POUs/outputs
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	if ((StartUpTimer < 20000) &&
	    (IO_VBPlus > 8000))
	    {
	    StartUpTimer ++;
	    }
	    else if (IO_VBPlus <= 8000)
	    {
	    StartUpTimer = 0;
	    }
	    
	    
	/*AC AUTO Logic*/
	    if ((SystemOn == 1) &&
	        (AutoMan == 0) &&
	        ((kennel1Temp > (p_ACSetPoint + p_ACDeadband)) || 
	        (kennel2Temp > (p_ACSetPoint + p_ACDeadband)) ||
	        (kennel3Temp > (p_ACSetPoint + p_ACDeadband)) ||
	        (kennel4Temp > (p_ACSetPoint + p_ACDeadband)) ||
	        (kennel5Temp > (p_ACSetPoint + p_ACDeadband)) ||
	        (kennel6Temp > (p_ACSetPoint + p_ACDeadband)) ||
	        (kennel7Temp > (p_ACSetPoint + p_ACDeadband)) ||
	        (kennel8Temp > (p_ACSetPoint + p_ACDeadband)))) 
	        {
	        AcOnAuto = 1;    
	        }   
	    else if
	        ((SystemOn == 0) ||
	        (AutoMan == 1) ||
	        ((kennel1Temp < (p_ACSetPoint - p_ACDeadband)) &&
	        (kennel2Temp < (p_ACSetPoint - p_ACDeadband)) &&
	        (kennel3Temp < (p_ACSetPoint - p_ACDeadband)) &&
	        (kennel4Temp < (p_ACSetPoint - p_ACDeadband)) &&
	        (kennel5Temp < (p_ACSetPoint - p_ACDeadband)) &&
	        (kennel6Temp < (p_ACSetPoint - p_ACDeadband)) &&
	        (kennel7Temp < (p_ACSetPoint - p_ACDeadband)) &&
	        (kennel8Temp < (p_ACSetPoint - p_ACDeadband))))
	        {
	        AcOnAuto = 0;    
	        }
	
	/*AC Output Logic */
	    if (((AcOnAuto) ||    
	        (AcOnMan)) &&
	        (IO_Heat == 0))
	        {
	        IO_AC = 1;
	        buttonF4_bitmap = 1;
	        }
	    else 
	        {
	        IO_AC = 0;
	         buttonF4_bitmap = 0;
	        }
	        
	/*Heat AUTO Logic*/
	    if ((SystemOn == 1) &&
	        (AutoMan == 0) &&
	        (((kennel1Temp < (p_HeatSetPoint - p_HeatDeadband)) && (kennel1Temp > -50)) || 
	        ((kennel2Temp < (p_HeatSetPoint - p_HeatDeadband)) && (kennel2Temp > -50)) ||
	        ((kennel3Temp < (p_HeatSetPoint - p_HeatDeadband)) && (kennel3Temp > -50))||
	        ((kennel4Temp < (p_HeatSetPoint - p_HeatDeadband)) && (kennel4Temp > -50))||
	        ((kennel5Temp < (p_HeatSetPoint - p_HeatDeadband)) && (kennel5Temp > -50)) ||
	        ((kennel6Temp < (p_HeatSetPoint - p_HeatDeadband)) && (kennel6Temp > -50)) ||
	        ((kennel7Temp < (p_HeatSetPoint - p_HeatDeadband)) && (kennel7Temp > -50)) ||
	        ((kennel8Temp < (p_HeatSetPoint - p_HeatDeadband)) && (kennel8Temp > -50)))) 
	        {
	        HeatOnAuto = 1;    
	        }   
	    else if
	        ((SystemOn == 0) ||
	        (AutoMan == 1) ||
	        ((kennel1Temp > (p_HeatSetPoint + p_HeatDeadband)) &&
	        (kennel2Temp > (p_HeatSetPoint + p_HeatDeadband)) &&
	        (kennel3Temp > (p_HeatSetPoint + p_HeatDeadband)) &&
	        (kennel4Temp > (p_HeatSetPoint + p_HeatDeadband)) &&
	        (kennel5Temp > (p_HeatSetPoint + p_HeatDeadband)) &&
	        (kennel6Temp > (p_HeatSetPoint + p_HeatDeadband)) &&
	        (kennel7Temp > (p_HeatSetPoint + p_HeatDeadband)) &&
	        (kennel8Temp > (p_HeatSetPoint + p_HeatDeadband))))
	        {
	        HeatOnAuto = 0;    
	        }
	    
	    /*Heat Output Logic */
	    if (((HeatOnAuto) ||    
	        (HeatOnMan)) &&
	        (IO_AC == 0))
	        {
	        IO_Heat = 1;
	         buttonF5_bitmap = 1;
	        }
	    else 
	        {
	        IO_Heat = 0;
	         buttonF5_bitmap = 0;
	        }
	
	/*Fan AUTO Logic*/
		if (((SystemOn == 1) && 
	        (AutoMan == 0)) ||
	        ((SystemOn == 1) && 
	        (AutoMan == 1) &&
	        (FanOnMan == 1))) //||
	        //((SystemOn == 1) && 
	        //(AutoMan == 1) &&
	        //(AcOnMan == 1)) ||
	        //((SystemOn == 1) && 
	        //(AutoMan == 1) &&
	        //(HeatOnMan == 1)))
	        {
	        FanOnAuto = 1; 
	        }
	    else
	        {
	        FanOnAuto = 0;     
	        }
	
	/*Fan Output Logic */
	    if ((FanOnAuto) ||    
	        (FanOnMan))
	        {
	        IO_Fan = 1;
	         buttonF3_bitmap = 1;
	        }
	    else 
	        {
	        IO_Fan = 0;
	         buttonF3_bitmap = 0;
	        }
	
	/*Interior Lights Output Logic*/
	    if (InteriorLightsOn == 1)
	        {
	        IO_InteriorLight = 1;
	         buttonF6_bitmap = 1;
	        }
	    else
	        {
	        IO_InteriorLight = 0;
	         buttonF6_bitmap = 0;
	        }
	        
	/*Side Lights Output Logic
	    if (SideLightsOn == 1)
	        {
	        IO_SideLight = 1;
	         buttonF7_bitmap = 1;
	        }
	    else
	        {
	        IO_SideLight = 0;
	         buttonF7_bitmap = 0;
	        }
	        */
	/*Rear Lights Output Logic
	    if (RearLightOn == 1)
	        {
	        IO_RearLight = 1;
	         buttonF8_bitmap = 1;
	        }
	    else
	        {
	        IO_RearLight = 0;
	         buttonF8_bitmap = 0;
	        }*/
	/*Strobe Light Output Logic*/
	    if (StrobeLightsOn == 1)
	        {
	        IO_StrobeLight = 1;
	         buttonF9_bitmap = 1;
	        }
	    else
	        {
	        IO_StrobeLight = 0;
	         buttonF9_bitmap = 0;
	        }  
	
	/*Strobe Pattern Pulse Output Logic*/
	    if (StrobePatternPulse == 1)
	        {
	        IO_StrobePattern = 1;
	         buttonF10_bitmap = 1;
	        }
	    else
	        {
	        IO_StrobePattern = 0;
	         buttonF10_bitmap = 0;
	        }  
	
	/*System On Button Indicator */
	    if (SystemOn == (TRUE))
	        {
	         buttonF1_bitmap = 1;
	        }
	    else
	        {
	        buttonF1_bitmap = 0;
	        }
	        
	/*Auto MANUAL Button Indicator */
	    if (AutoMan == 1)
	        {
	        buttonF2_bitmap = 2;
	        buttonF2_text = 0;
	        }
	    else
	        {
	        buttonF2_bitmap = 4; 
	        buttonF2_text = 1;
	        }
	/*Buzzer Logic*/
	    if ((((kennel1Alarm == 1) && (kennel1Alarm_Silence ==0)) ||
	        ((kennel2Alarm == 1) && (kennel2AlarmBuzzer_Silence ==0)) ||
	        ((kennel3Alarm == 1) && (kennel3AlarmBuzzer_Silence ==0))||
	        ((kennel4Alarm == 1) && (kennel4AlarmBuzzer_Silence ==0))||
	        ((kennel5Alarm == 1) && (kennel5AlarmBuzzer_Silence ==0))||
	        ((kennel6Alarm == 1) && (kennel6AlarmBuzzer_Silence ==0))||
	        ((kennel7Alarm == 1) && (kennel7AlarmBuzzer_Silence ==0))||
	        ((kennel8Alarm == 1) && (kennel8AlarmBuzzer_Silence ==0)))&&
	        (StartUpTimer > 10000) &&
	        (IO_VBPlus > 8000))
	        {
	        BuzzerTera = 1;
	        AlarmMessage = 1;
	        }
	    else
	        {
	         BuzzerTera = 0;
	         AlarmMessage = 0;
	        }
	   
	    
	    
	
	}

	/* end of PROGRAM body */
}



#endif /* INCLUDE__VT3_POU__OUTPUTS_C */

/* end of file */
