PROGRAM _CYCLIC
<?xml version="1.0"?>
<?AutomationStudio Version=3.0.71?>
<!-- Automation Studio Generated XML Section -->
<networks maxcolumn="0">
	<network label="" comment="" row="2" column="0" commented="0">
		<row>
			<contact type="open" name="gdi.PressureSwitch"/>
			<line/>
			<line/>
			<coil type="set" name="gdo.RedStackLight"/>
		</row>
		<row>
			<empty or="true"/>
			<line/>
			<line/>
			<coil type="set" name="gExecute"/>
		</row>
	</network>
</networks>
END_PROGRAM

